# Redirect all HTTP and www to HTTPS non-www
server {
    listen 80;
    listen [::]:80;
    server_name wg-management-dashboard.duckdns.org www.wg-management-dashboard.duckdns.org;
    return 301 https://wg-management-dashboard.duckdns.org$request_uri;
}

server {
    server_name wg-management-dashboard.duckdns.org www.wg-management-dashboard.duckdns.org;
    root /usr/local/var/www/vpn-dashboard;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /api/socket.io/ {
        proxy_pass http://127.0.0.1:3000/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen [::]:443 ssl ipv6only=on;  # managed by Certbot
    listen 443 ssl;                    # managed by Certbot

    ssl_certificate /etc/letsencrypt/live/wg-management-dashboard.duckdns.org/fullchain.pem;  # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/wg-management-dashboard.duckdns.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;                                         # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;                                           # managed by Certbot
}
